"use client";
import {useCallback,useEffect,useState} from "react"; import {BarChart3,RefreshCw,TrendingUp,Send,Reply,ShieldAlert,Clock} from "lucide-react"; import {BlueprintNav} from "@/components/blueprint-nav"; import {getSupabaseBrowser} from "@/lib/supabase-browser";
type Row={id:string;name:string;country:string;campaign_group:string;status:string;metrics:any};
export default function CampaignIntelligence(){const [token,setToken]=useState("");const [rows,setRows]=useState<Row[]>([]);const [totals,setTotals]=useState<any>({});const [countries,setCountries]=useState<string[]>([]);const [groups,setGroups]=useState<string[]>([]);const [country,setCountry]=useState("");const [group,setGroup]=useState("");const [busy,setBusy]=useState(false);const [err,setErr]=useState("");
const load=useCallback(async(t=token)=>{if(!t)return;setBusy(true);try{const p=new URLSearchParams({country,group});const r=await fetch("/api/campaign-intelligence?"+p,{headers:{Authorization:"Bearer "+t}});const d=await r.json();if(!r.ok)throw new Error(d.error);setRows(d.campaigns||[]);setTotals(d.totals||{});setCountries(d.filters?.countries||[]);setGroups(d.filters?.groups||[])}catch(e){setErr(e instanceof Error?e.message:"Unable to load intelligence")}finally{setBusy(false)}},[country,group,token]);useEffect(()=>{getSupabaseBrowser().auth.getSession().then(({data})=>{if(data.session){setToken(data.session.access_token);load(data.session.access_token)}})},[]);
const cards=[["Recipients",totals.recipients||0,Send],["Sent",totals.sent||0,Send],["Opens",totals.opens||0,TrendingUp],["Replies",totals.replies||0,Reply],["Positive",totals.positive||0,TrendingUp],["Bounces",totals.bounces||0,ShieldAlert]];
return <main className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50 p-4 text-slate-900 md:p-8"><div className="mx-auto max-w-[1500px]"><BlueprintNav/><header className="mb-5 flex flex-wrap items-center justify-between gap-4 rounded-3xl border border-blue-100 bg-white/85 p-6 shadow-sm"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.2em] text-indigo-500"><BarChart3 size={15}/> Outbound performance</div><h1 className="mt-2 text-3xl font-black">Campaign Intelligence</h1><p className="mt-1 text-sm text-slate-500">Country, campaign group and campaign-level performance with reply and suppression outcomes.</p></div><button onClick={()=>load()} className="rounded-xl border border-blue-100 p-3 text-indigo-600">{busy?<RefreshCw className="animate-spin" size={18}/>:<RefreshCw size={18}/>}</button></header>
<div className="mb-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{cards.map(([label,n,Icon])=><div key={String(label)} className="rounded-2xl border border-blue-100 bg-white p-4 shadow-sm transition hover:-translate-y-1"><Icon size={16} className="text-indigo-500"/><div className="mt-2 text-2xl font-black tabular-nums">{n}</div><div className="text-[10px] font-black uppercase tracking-wider text-slate-500">{label}</div></div>)}</div>
<div className="mb-5 flex flex-wrap gap-3 rounded-2xl border border-blue-100 bg-white p-4"><select value={country} onChange={e=>setCountry(e.target.value)} className="rounded-xl border border-blue-100 p-2.5 text-sm"><option value="">All countries</option>{countries.map(x=><option key={x}>{x}</option>)}</select><select value={group} onChange={e=>setGroup(e.target.value)} className="rounded-xl border border-blue-100 p-2.5 text-sm"><option value="">All groups</option>{groups.map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>load()} className="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-bold text-white">Apply filters</button></div>
{err&&<div className="mb-4 rounded-2xl bg-rose-50 p-4 text-sm text-rose-700">{err}</div>}
<div className="overflow-hidden rounded-3xl border border-blue-100 bg-white shadow-sm"><div className="overflow-auto"><table className="w-full min-w-[1100px] text-left text-sm"><thead className="bg-blue-50 text-[10px] uppercase tracking-wider text-slate-500"><tr>{["Campaign","Country","Group","Status","Recipients","Eligible","Sent","Opens","Replies","Positive","Neutral","Negative","Bounces","Unsub","Completion"].map(x=><th key={x} className="whitespace-nowrap p-3 font-black">{x}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id} className="border-t border-blue-50 transition hover:bg-blue-50/50 animate-[riseIn_.35s_ease-out]" style={{animationDelay:`${i*35}ms`}}><td className="p-3 font-bold">{r.name}</td><td className="p-3">{r.country}</td><td className="p-3">{r.campaign_group}</td><td className="p-3"><span className="rounded-full bg-indigo-50 px-2 py-1 text-xs font-bold text-indigo-700">{r.status}</span></td><td className="p-3">{r.metrics.recipients}</td><td className="p-3">{r.metrics.eligible}</td><td className="p-3">{r.metrics.sent}</td><td className="p-3">{r.metrics.opens}</td><td className="p-3">{r.metrics.replies}</td><td className="p-3 text-emerald-600 font-bold">{r.metrics.positive}</td><td className="p-3">{r.metrics.neutral}</td><td className="p-3">{r.metrics.negative}</td><td className="p-3 text-rose-600">{r.metrics.bounces}</td><td className="p-3">{r.metrics.unsubscribes}</td><td className="p-3 text-xs text-slate-500">{r.metrics.completion_time?Math.round(r.metrics.completion_time/60000)+" min":"—"}</td></tr>)}</tbody></table>{!rows.length&&<div className="p-12 text-center text-sm text-slate-400">No campaign data matches these filters.</div>}</div></div></div></main>}
