"use client";
import {useEffect,useMemo,useState} from "react";
import {getSupabaseBrowser} from "@/lib/supabase-browser";
import {Mail,Plus,RefreshCw,Send,Users,ShieldCheck,CheckCircle2,AlertTriangle} from "lucide-react";
type Campaign={id:string;name:string;country:string;campaign_group:string;subject:string;body:string;status:string};
type Lead={id:string;email:string;company_name:string;first_name:string;last_name:string;country:string;current_status:string;suppression_reason:string|null;lead_owner:string|null};
type Account={id:string;email:string;employee_id:string|null;health_status:string;daily_send_limit:number;hourly_send_limit:number;total_sent:number};
export default function MailMergePage(){
 const supabase=useMemo(()=>getSupabaseBrowser(),[]); const [token,setToken]=useState(""); const [campaigns,setCampaigns]=useState<Campaign[]>([]); const [accounts,setAccounts]=useState<Account[]>([]);
 const [campaignId,setCampaignId]=useState(""); const [leads,setLeads]=useState<Lead[]>([]); const [selected,setSelected]=useState<string[]>([]); const [sender,setSender]=useState("");
 const [form,setForm]=useState({name:"",country:"USA",campaign_group:"Fresh Outreach",subject:"",body:"Hi {{first_name}},\n\nI’m reaching out regarding {{company_name}}."}); const [q,setQ]=useState(""); const [country,setCountry]=useState("USA"); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState(""); const [err,setErr]=useState("");
 async function api(path:string,options?:RequestInit){const r=await fetch(path,{...options,headers:{Authorization:"Bearer "+token,"Content-Type":"application/json",...(options?.headers||{})}});const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");return d}
 async function load(){if(!token)return;const d=await api("/api/mail-merge");setCampaigns(d.campaigns||[]);setAccounts(d.accounts||[]);if(!sender&&d.accounts?.[0])setSender(d.accounts[0].id)}
 async function loadLeads(){if(!token)return;const p=new URLSearchParams({q,country,page:"1",pageSize:"100"});const d=await api("/api/leads?"+p);setLeads((d.leads||[]).filter((x:Lead)=>!x.suppression_reason&&!["Bounced","Unsubscribed","Suppressed","Positive","Neutral","Negative"].includes(x.current_status)))}
 useEffect(()=>{supabase.auth.getSession().then(async({data})=>{if(data.session){setToken(data.session.access_token)}})},[supabase]);
 useEffect(()=>{if(token){load().catch(e=>setErr(e.message));loadLeads().catch(e=>setErr(e.message))}},[token]);
 async function create(){setBusy(true);setErr("");setMsg("");try{const d=await api("/api/mail-merge",{method:"POST",body:JSON.stringify(form)});setCampaigns(x=>[d.campaign,...x]);setCampaignId(d.campaign.id);setMsg("Campaign created. Select recipients below.")}catch(e){setErr(e instanceof Error?e.message:"Create failed")}finally{setBusy(false)}}
 async function addRecipients(){if(!campaignId||!sender||!selected.length)return;setBusy(true);setErr("");try{const d=await api("/api/mail-merge/recipients",{method:"POST",body:JSON.stringify({campaignId,leadIds:selected,senderAccountId:sender})});setMsg("Added "+d.added+" recipients. "+d.blocked+" blocked.");setSelected([])}catch(e){setErr(e instanceof Error?e.message:"Recipient selection failed")}finally{setBusy(false)}}
 async function queue(){if(!campaignId)return;setBusy(true);try{const d=await api("/api/mail-merge/queue",{method:"POST",body:JSON.stringify({campaignId})});setMsg(d.message)}catch(e){setErr(e instanceof Error?e.message:"Queue failed")}finally{setBusy(false)}}
 async function send(){if(!campaignId)return;setBusy(true);try{const d=await api("/api/mail-merge/send",{method:"POST",body:JSON.stringify({campaignId})});setMsg("Dispatch: "+d.sent+" sent, "+d.failed+" failed.");await load()}catch(e){setErr(e instanceof Error?e.message:"Send failed")}finally{setBusy(false)}}
 const active=campaigns.find(x=>x.id===campaignId);
 const selectedAccount=accounts.find(x=>x.id===sender);
 return <main className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50 p-4 md:p-8 text-slate-900"><div className="mx-auto max-w-[1500px] space-y-6">
  <header className="flex flex-wrap items-center justify-between gap-4 rounded-3xl border border-blue-100 bg-white/85 p-6 shadow-sm"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.2em] text-indigo-500"><ShieldCheck size={15}/> BookAirfreight · Outbound</div><h1 className="mt-2 text-3xl font-black">Mail Merge Command Center</h1><p className="mt-1 text-sm text-slate-500">Build, reconcile, queue and dispatch controlled campaigns from the Master Lead Sheet.</p></div><button onClick={()=>{load();loadLeads()}} className="rounded-xl border border-blue-100 p-3 text-indigo-600"><RefreshCw size={18}/></button></header>
  {(msg||err)&&<div className={err?"rounded-2xl border border-rose-100 bg-rose-50 p-4 text-sm text-rose-700":"rounded-2xl border border-emerald-100 bg-emerald-50 p-4 text-sm text-emerald-700"}>{err||msg}</div>}
  <section className="grid gap-5 lg:grid-cols-[380px_minmax(0,1fr)]">
   <div className="rounded-3xl border border-blue-100 bg-white p-5 shadow-sm space-y-4"><div className="flex items-center gap-2"><Plus size={18} className="text-indigo-500"/><h2 className="font-black">Campaign</h2></div>
    <input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Campaign name" className="w-full rounded-xl border border-blue-100 p-3 text-sm"/>
    <input value={form.country} onChange={e=>setForm({...form,country:e.target.value})} placeholder="Country" className="w-full rounded-xl border border-blue-100 p-3 text-sm"/>
    <select value={form.campaign_group} onChange={e=>setForm({...form,campaign_group:e.target.value})} className="w-full rounded-xl border border-blue-100 p-3 text-sm">{["Fresh Outreach","Follow-up 1","Follow-up 2","Follow-up 3","Custom"].map(x=><option key={x}>{x}</option>)}</select>
    <input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})} placeholder="Subject — use {{first_name}} / {{company_name}}" className="w-full rounded-xl border border-blue-100 p-3 text-sm"/>
    <textarea value={form.body} onChange={e=>setForm({...form,body:e.target.value})} className="min-h-48 w-full rounded-xl border border-blue-100 p-3 text-sm leading-6"/>
    <button disabled={busy} onClick={create} className="w-full rounded-xl bg-indigo-600 px-4 py-3 font-bold text-white disabled:opacity-40"><Plus size={16} className="mr-2 inline"/>Create Campaign</button>
    <div className="border-t border-blue-50 pt-4"><div className="mb-2 text-xs font-black uppercase tracking-wider text-slate-400">Existing campaigns</div>{campaigns.map(c=><button key={c.id} onClick={()=>setCampaignId(c.id)} className={"mb-2 w-full rounded-xl p-3 text-left "+(c.id===campaignId?"bg-indigo-50 ring-1 ring-indigo-200":"bg-slate-50")}><div className="font-bold">{c.name}</div><div className="mt-1 text-xs text-slate-500">{c.country} · {c.campaign_group} · {c.status}</div></button>)}</div>
   </div>
   <div className="space-y-5">
    <div className="rounded-3xl border border-blue-100 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-black">Recipient selection</h2><p className="text-sm text-slate-500">{active?active.name:"Create/select a campaign first"}</p></div><div className="text-right"><div className="text-2xl font-black">{selected.length}</div><div className="text-[10px] font-bold uppercase text-slate-400">Selected</div></div></div>
     <div className="mt-4 grid gap-3 md:grid-cols-[1fr_140px_220px]"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")loadLeads()}} placeholder="Search company / email / name" className="rounded-xl border border-blue-100 p-3 text-sm"/><input value={country} onChange={e=>setCountry(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")loadLeads()}} className="rounded-xl border border-blue-100 p-3 text-sm"/><select value={sender} onChange={e=>setSender(e.target.value)} className="rounded-xl border border-blue-100 p-3 text-sm">{accounts.map(a=><option key={a.id} value={a.id}>{a.email} · {a.health_status}</option>)}</select></div>
     <div className="mt-4 max-h-80 overflow-auto rounded-2xl border border-blue-50"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-blue-50 text-xs uppercase text-slate-500"><tr><th className="p-3"></th><th className="p-3">Recipient</th><th className="p-3">Company</th><th className="p-3">Country</th><th className="p-3">Status</th></tr></thead><tbody>{leads.map(l=><tr key={l.id} className="border-t border-blue-50"><td className="p-3"><input type="checkbox" checked={selected.includes(l.id)} onChange={e=>setSelected(s=>e.target.checked?[...s,l.id]:s.filter(x=>x!==l.id))}/></td><td className="p-3"><div className="font-semibold">{l.first_name} {l.last_name}</div><div className="text-xs text-indigo-600">{l.email}</div></td><td className="p-3">{l.company_name||"—"}</td><td className="p-3">{l.country}</td><td className="p-3 text-xs">{l.current_status}</td></tr>)}</tbody></table></div>
     <div className="mt-4 flex flex-wrap gap-2"><button disabled={!active||!selected.length||busy} onClick={addRecipients} className="rounded-xl bg-slate-900 px-4 py-3 text-sm font-bold text-white disabled:opacity-40"><Users size={16} className="mr-2 inline"/>Add to Campaign</button><button disabled={!active||busy} onClick={queue} className="rounded-xl bg-indigo-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-40">Queue ≤10</button><button disabled={!active||busy} onClick={send} className="rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white disabled:opacity-40"><Send size={16} className="mr-2 inline"/>Dispatch</button></div>
    </div>
    <div className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl border border-blue-100 bg-white p-4"><div className="text-xs font-bold uppercase text-slate-400">Sender</div><div className="mt-2 font-black">{selectedAccount?.email||"—"}</div><div className="mt-1 text-xs text-slate-500">{selectedAccount?.health_status||""} · {selectedAccount?.daily_send_limit||0}/day</div></div><div className="rounded-2xl border border-blue-100 bg-white p-4"><div className="text-xs font-bold uppercase text-slate-400">Safety cap</div><div className="mt-2 font-black">10 recipients</div><div className="mt-1 text-xs text-slate-500">per subject/account/campaign</div></div><div className="rounded-2xl border border-blue-100 bg-white p-4"><div className="text-xs font-bold uppercase text-slate-400">Provider</div><div className="mt-2 font-black">Controlled dispatch</div><div className="mt-1 flex items-center gap-1 text-xs text-amber-600"><AlertTriangle size={13}/> requires configured provider</div></div></div>
   </div>
  </section>
 </div></main>
}
