"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import * as XLSX from "xlsx";
import { getSupabaseBrowser } from "@/lib/supabase-browser";
import { ArrowDownToLine, CheckCircle2, ClipboardPaste, LoaderCircle, RefreshCw, Search, ShieldCheck, Users } from "lucide-react";

type Lead = { id:string; email:string; country:string; company_name:string; first_name:string; last_name:string; title:string; main_industry:string; ecommerce_platform_used:string; lead_owner:string|null; current_status:string; response_classification:string|null; suppression_reason:string|null; created_at:string; updated_at:string; last_contacted_at:string|null; last_replied_at:string|null; };
type ImportResult = { row_number:number; email:string; company_name:string; result:"added"|"skipped"; reason:string };
const STATUS = ["New","Qualified","Fresh Outreach","Follow-up 1","Follow-up 2","Follow-up 3","Positive","Neutral","Negative","Needs Review","Suppressed"];
const dateTime=(s:string|null|undefined)=>s?new Date(s).toLocaleString():"—";

export function MasterLeadWorkspace(){
 const supabase=useMemo(()=>getSupabaseBrowser(),[]);
 const [token,setToken]=useState("");
 const [leads,setLeads]=useState<Lead[]>([]);
 const [total,setTotal]=useState(0);
 const [q,setQ]=useState("");
 const [country,setCountry]=useState("");
 const [status,setStatus]=useState("");
 const [paste,setPaste]=useState("");
 const [busy,setBusy]=useState(false);
 const [message,setMessage]=useState("");
 const [report,setReport]=useState<{batchId:string;total_rows:number;added_count:number;skipped_existing:number;skipped_in_batch:number;skipped_invalid:number;skipped_missing_country:number;completed_at:string;results:ImportResult[]}|null>(null);
 const [page,setPage]=useState(1);
 const [error,setError]=useState("");
 const load=useCallback(async(t:string,p=1)=>{setError("");const params=new URLSearchParams({q,country,status,page:String(p),pageSize:"50"});const res=await fetch("/api/leads?"+params,{headers:{Authorization:"Bearer "+t}});const data=await res.json();if(!res.ok)throw new Error(data.error||"Could not load leads");setLeads(data.leads||[]);setTotal(data.total||0);},[q,country,status]);
 useEffect(()=>{let active=true;(async()=>{const {data}=await supabase.auth.getSession();if(!active)return;if(!data.session){setError("Sign in through the existing BookAirfreight Outbound OS first, then open Master Leads.");return}setToken(data.session.access_token);try{await load(data.session.access_token)}catch(e){setError(e instanceof Error?e.message:"Unable to load leads")}})();return()=>{active=false}},[supabase,load]);
 useEffect(()=>{if(token)load(token,page).catch(e=>setError(e instanceof Error?e.message:"Unable to load leads"))},[token,q,country,status,page,load]);
 async function importRows(){if(!token||!paste.trim())return;setBusy(true);setMessage("");setReport(null);setError("");try{
   const wb=XLSX.read(paste,{type:"string"});const sheet=wb.Sheets[wb.SheetNames[0]];const grid=XLSX.utils.sheet_to_json<unknown[]>(sheet,{header:1,defval:""});if(grid.length<2)throw new Error("Paste a header row followed by at least one recipient row.");
   const headers=(grid[0] as unknown[]).map(v=>String(v??"").trim());const rows=grid.slice(1).filter(r=>(r as unknown[]).some(v=>String(v??"").trim())).map(r=>Object.fromEntries(headers.map((h,i)=>[h,String((r as unknown[])[i]??"")])));
   const res=await fetch("/api/leads",{method:"POST",headers:{Authorization:"Bearer "+token,"Content-Type":"application/json"},body:JSON.stringify({rows,fileName:"Clipboard paste"})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Import failed");setReport(data);setMessage("Import reconciled successfully. New recipients were added; existing or invalid rows were skipped.");setPaste("");setPage(1);await load(token,1);
 }catch(e){setError(e instanceof Error?e.message:"Import failed")}finally{setBusy(false)}}
 async function classify(lead:Lead,next:string){if(!token)return;setBusy(true);setError("");try{const res=await fetch("/api/leads",{method:"PATCH",headers:{Authorization:"Bearer "+token,"Content-Type":"application/json"},body:JSON.stringify({id:lead.id,status:next})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Could not update lead");setLeads(old=>old.map(x=>x.id===lead.id?data.lead:x));setMessage("Lead status saved. Outreach eligibility has been updated.");}catch(e){setError(e instanceof Error?e.message:"Update failed")}finally{setBusy(false)}}
 function downloadReport(){if(!report)return;const csv=["Row,Email,Company,Result,Reason",...report.results.map(r=>[r.row_number,r.email,r.company_name,r.result,r.reason].map(v=>'"'+String(v??"").replace(/"/g,'""')+'"').join(","))].join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download="lead-import-reconciliation-"+report.batchId+".csv";a.click();URL.revokeObjectURL(url)}
 const added=report?.added_count||0;
 return <main className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50 p-4 text-slate-900 md:p-8">
  <div className="mx-auto max-w-[1600px] space-y-6">
   <header className="flex flex-wrap items-center justify-between gap-4 rounded-3xl border border-blue-100 bg-white/80 p-6 shadow-sm backdrop-blur">
    <div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.22em] text-indigo-500"><ShieldCheck size={15}/> BookAirfreight · Lead Operations</div><h1 className="mt-2 text-3xl font-black tracking-tight">Master Lead Sheet</h1><p className="mt-1 text-sm text-slate-500">Unique recipient registry · country-wise outreach · response and suppression controls</p></div>
    <div className="flex items-center gap-3 rounded-2xl bg-blue-50 px-4 py-3"><Users className="text-indigo-500"/><div><div className="text-xl font-black tabular-nums">{total.toLocaleString()}</div><div className="text-[10px] font-bold uppercase tracking-wider text-slate-500">Recipients in current result</div></div></div>
   </header>
   <section className="grid gap-5 xl:grid-cols-[minmax(320px,.8fr)_minmax(0,1.2fr)]">
    <div className="rounded-3xl border border-blue-100 bg-white p-5 shadow-sm">
     <div className="flex items-center gap-2"><ClipboardPaste size={18} className="text-indigo-500"/><h2 className="text-lg font-black">Paste Excel / Google Sheets</h2></div>
     <p className="mt-2 text-sm text-slate-500">Include the column headers in the first row. Existing recipient emails are skipped and never overwrite ownership or history.</p>
     <textarea value={paste} onChange={e=>setPaste(e.target.value)} placeholder="Paste your header row and lead rows here…" className="mt-4 min-h-64 w-full resize-y rounded-2xl border border-blue-100 bg-blue-50/60 p-4 font-mono text-xs leading-6 outline-none transition focus:border-indigo-300 focus:ring-4 focus:ring-indigo-100"/>
     <div className="mt-3 flex flex-wrap items-center justify-between gap-3"><span className="text-xs text-slate-400">{paste.trim()?paste.trim().split(/\r?\n/).length+" pasted lines":"Waiting for spreadsheet data"}</span><button disabled={busy||!paste.trim()} onClick={importRows} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white shadow-lg shadow-indigo-200 transition hover:-translate-y-0.5 disabled:opacity-40">{busy?<LoaderCircle className="animate-spin" size={16}/>:<ClipboardPaste size={16}/>} Validate & Import</button></div>
     {message&&<div className="mt-4 flex items-start gap-2 rounded-xl border border-emerald-100 bg-emerald-50 p-3 text-sm text-emerald-700 animate-[riseIn_.3s_ease-out]"><CheckCircle2 size={17} className="mt-0.5 shrink-0"/>{message}</div>}
     {error&&<div role="alert" className="mt-4 rounded-xl border border-rose-100 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
    </div>
    <div className="rounded-3xl border border-blue-100 bg-white p-5 shadow-sm">
     <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-black">Import reconciliation</h2><p className="text-sm text-slate-500">Added / skipped counts with row-level reasons</p></div>{report&&<button onClick={downloadReport} className="inline-flex items-center gap-2 rounded-xl border border-blue-100 px-3 py-2 text-sm font-bold text-indigo-600 hover:bg-blue-50"><ArrowDownToLine size={16}/> Download CSV</button>}</div>
     {report?<><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3">{[["Processed",report.total_rows,"text-slate-900"],["Added",report.added_count,"text-emerald-600"],["Existing",report.skipped_existing,"text-amber-600"],["In-batch duplicates",report.skipped_in_batch,"text-amber-600"],["Invalid email / save",report.skipped_invalid,"text-rose-600"],["Missing country",report.skipped_missing_country,"text-rose-600"]].map(([label,count,color])=><div key={String(label)} className="rounded-2xl bg-slate-50 p-4"><div className={"text-2xl font-black tabular-nums "+color}>{Number(count).toLocaleString()}</div><div className="mt-1 text-[10px] font-bold uppercase tracking-wider text-slate-500">{label}</div></div>)}</div><p className="mt-4 text-xs text-slate-400">Completed {dateTime(report.completed_at)} · Batch {report.batchId.slice(0,8)}</p></>:<div className="mt-5 grid min-h-64 place-items-center rounded-2xl border border-dashed border-blue-100 bg-blue-50/30 text-center"><div><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-white text-indigo-500 shadow-sm"><RefreshCw size={20}/></div><p className="mt-3 font-bold text-slate-600">Import results will appear here</p><p className="mt-1 text-xs text-slate-400">A reconciliation report is generated after each import.</p></div></div>}
    </div>
   </section>
   <section className="overflow-hidden rounded-3xl border border-blue-100 bg-white shadow-sm">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-blue-50 p-5"><div><h2 className="text-lg font-black">Recipient Registry</h2><p className="text-sm text-slate-500">Search by email, company, person, or country</p></div><div className="flex flex-wrap gap-2"><label className="relative"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><input value={q} onChange={e=>{setPage(1);setQ(e.target.value)}} placeholder="Search leads…" className="w-56 rounded-xl border border-blue-100 py-2.5 pl-9 pr-3 text-sm outline-none focus:border-indigo-300"/></label><input value={country} onChange={e=>{setPage(1);setCountry(e.target.value)}} placeholder="Country filter" className="w-36 rounded-xl border border-blue-100 px-3 py-2.5 text-sm outline-none focus:border-indigo-300"/><select value={status} onChange={e=>{setPage(1);setStatus(e.target.value)}} className="rounded-xl border border-blue-100 px-3 py-2.5 text-sm"><option value="">All statuses</option>{STATUS.map(s=><option key={s}>{s}</option>)}</select></div></div>
    <div className="max-h-[65vh] overflow-auto"><table className="w-full min-w-[1250px] border-collapse text-left text-sm"><thead className="sticky top-0 z-10 bg-blue-50 text-[10px] uppercase tracking-wider text-slate-500"><tr>{["Company / Recipient","Country","Contact","Industry","Ecommerce","Lead Owner","Status / Response","Suppression","Added","Updated","Last Contact","Last Reply"].map(h=><th key={h} className="whitespace-nowrap px-4 py-3 font-black">{h}</th>)}</tr></thead><tbody>{leads.map(lead=><tr key={lead.id} className="border-t border-blue-50 transition-colors hover:bg-blue-50/50"><td className="px-4 py-3"><div className="font-bold">{lead.company_name||"—"}</div><div className="mt-1 text-xs text-indigo-600">{lead.email}</div></td><td className="px-4 py-3">{lead.country}</td><td className="px-4 py-3">{[lead.first_name,lead.last_name].filter(Boolean).join(" ")||"—"}<div className="text-xs text-slate-400">{lead.title}</div></td><td className="px-4 py-3">{lead.main_industry||"—"}</td><td className="px-4 py-3">{lead.ecommerce_platform_used||"—"}</td><td className="px-4 py-3 text-xs">{lead.lead_owner?lead.lead_owner.slice(0,8):"—"}</td><td className="px-4 py-3"><select aria-label={"Status for "+lead.email} disabled={busy} value={lead.current_status} onChange={e=>classify(lead,e.target.value)} className="rounded-lg border border-blue-100 px-2 py-1.5 text-xs"><option value={lead.current_status}>{lead.current_status}</option>{STATUS.filter(s=>s!==lead.current_status).map(s=><option key={s}>{s}</option>)}</select></td><td className="max-w-48 px-4 py-3 text-xs">{lead.suppression_reason?<span className="rounded-full bg-rose-50 px-2 py-1 text-rose-700">{lead.suppression_reason}</span>:"—"}</td><td className="whitespace-nowrap px-4 py-3 text-xs text-slate-500">{dateTime(lead.created_at)}</td><td className="whitespace-nowrap px-4 py-3 text-xs text-slate-500">{dateTime(lead.updated_at)}</td><td className="whitespace-nowrap px-4 py-3 text-xs text-slate-500">{dateTime(lead.last_contacted_at)}</td><td className="whitespace-nowrap px-4 py-3 text-xs text-slate-500">{dateTime(lead.last_replied_at)}</td></tr>)}</tbody></table>{leads.length===0&&<div className="p-12 text-center text-sm text-slate-400">No recipients match these filters.</div>}</div>
    <div className="flex items-center justify-between border-t border-blue-50 p-4 text-xs text-slate-500"><span>Showing {leads.length} of {total.toLocaleString()} recipients</span><div className="flex gap-2"><button disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))} className="rounded-lg border border-blue-100 px-3 py-2 disabled:opacity-30">Previous</button><span className="px-2 py-2">Page {page}</span><button disabled={page*50>=total} onClick={()=>setPage(p=>p+1)} className="rounded-lg border border-blue-100 px-3 py-2 disabled:opacity-30">Next</button></div></div>
   </section>
  </div>
 </main>;
}
