"use client";
import {useState} from "react";
import {FREIGHT_INTELLIGENCE_REGIONS} from "@/lib/freight-intelligence";
import {getSupabaseBrowser} from "@/lib/supabase-browser";
export default function TestIntelligence(){
 const supabase=getSupabaseBrowser();
 const [region,setRegion]=useState("us"); const [loading,setLoading]=useState(false); const [data,setData]=useState<any>(null); const [error,setError]=useState("");
 async function run(){setLoading(true);setError("");try{const {data:sessionData}=await supabase.auth.getSession();if(!sessionData.session)throw new Error("Please sign in to Outbound OS first.");const r=await fetch("/api/intelligence/research",{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+sessionData.session.access_token},body:JSON.stringify({regions:[region],activities:[]})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Research failed");setData(j)}catch(e){setError(e instanceof Error?e.message:"Research failed")}finally{setLoading(false)}}
 const result=data?.regions?.[0];
 return <main className="min-h-screen bg-[#eef6ff] p-8 text-[#19345a]"><div className="mx-auto max-w-6xl space-y-6"><header className="rounded-3xl border border-blue-200 bg-white p-6"><p className="text-xs font-black uppercase tracking-[.3em] text-cyan-600">Freight Outreach Intelligence</p><h1 className="mt-2 text-4xl font-black">Market research test</h1><p className="mt-2 text-sm text-slate-500">Deterministic research. No AI API.</p><div className="mt-5 flex gap-2"><select value={region} onChange={e=>setRegion(e.target.value)} className="rounded-xl border border-blue-200 bg-blue-50 px-3 py-2">{FREIGHT_INTELLIGENCE_REGIONS.map(r=><option key={r.id} value={r.id}>{r.label}</option>)}</select><button onClick={run} disabled={loading} className="rounded-xl bg-[#4d5cff] px-4 py-2 font-black text-white">{loading?"Researching...":"Run research"}</button></div></header>{error&&<div className="rounded-xl bg-red-50 p-4 text-red-700">{error}</div>}{result&&<section className="grid gap-4 md:grid-cols-2">{result.topics.map((t:any)=><article key={t.id} className="rounded-2xl border border-blue-100 bg-white p-5"><div className="flex justify-between gap-3"><h2 className="font-black">{t.label}</h2><b>Evidence {t.evidenceScore}</b></div><p className="mt-3 text-sm text-slate-600">{t.angle}</p><p className="mt-3 text-xs font-bold text-slate-500">{t.marketSources} market sources · {t.internal.mentions} internal mentions · {t.internal.responses} internal responses</p></article>)}</section>}</div></main>
}