"use client";
import {useCallback,useEffect,useState} from "react"; import {HeartPulse,RefreshCw,ShieldCheck,PauseCircle,Activity} from "lucide-react"; import {BlueprintNav} from "@/components/blueprint-nav"; import {getSupabaseBrowser} from "@/lib/supabase-browser";
type Row={id:string;email:string;health_status:string;daily_send_limit:number;hourly_send_limit:number;total_sent:number;metrics:{attempted:number;accepted:number;failures:number;hard_bounces:number;soft_bounces:number;opens:number;replies:number;unsubscribes:number;auth_ok:boolean;recent_events:number;weekly_events:number}};
const pct=(a:number,b:number)=>b?Math.round(a/b*100):0;
export default function AccountHealth(){const [token,setToken]=useState("");const [rows,setRows]=useState<Row[]>([]);const [busy,setBusy]=useState(false);const [err,setErr]=useState("");
const load=useCallback(async(t=token)=>{if(!t)return;setBusy(true);try{const r=await fetch("/api/account-health",{headers:{Authorization:"Bearer "+t}});const d=await r.json();if(!r.ok)throw new Error(d.error);setRows(d.accounts||[])}catch(e){setErr(e instanceof Error?e.message:"Unable to load health")}finally{setBusy(false)}}
useEffect(()=>{getSupabaseBrowser().auth.getSession().then(({data})=>{if(data.session){setToken(data.session.access_token);load(data.session.access_token)}})},[load]);
const summary={healthy:rows.filter(x=>x.health_status==="Healthy").length,watch:rows.filter(x=>x.health_status==="Watch").length,paused:rows.filter(x=>x.health_status==="Paused").length};
return <main className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-indigo-50 p-4 text-slate-900 md:p-8"><div className="mx-auto max-w-[1500px]"><BlueprintNav/><header className="mb-5 flex flex-wrap items-center justify-between gap-4 rounded-3xl border border-blue-100 bg-white/85 p-6 shadow-sm"><div><div className="flex items-center gap-2 text-xs font-black uppercase tracking-[.2em] text-indigo-500"><HeartPulse size={15}/> Deliverability control</div><h1 className="mt-2 text-3xl font-black">Account Health</h1><p className="mt-1 text-sm text-slate-500">Per-account sending safety, provider events, suppression activity and directional health.</p></div><button onClick={()=>load()} className="rounded-xl border border-blue-100 p-3 text-indigo-600 transition hover:-translate-y-0.5">{busy?<RefreshCw className="animate-spin" size={18}/>:<RefreshCw size={18}/>}</button></header>
<div className="mb-5 grid gap-3 sm:grid-cols-3">{[["Healthy",summary.healthy,"text-emerald-600","bg-emerald-50"],["Watch",summary.watch,"text-amber-600","bg-amber-50"],["Paused",summary.paused,"text-rose-600","bg-rose-50"]].map(([l,n,c,b])=><div key={String(l)} className={`rounded-2xl border border-blue-100 ${b} p-5 transition hover:-translate-y-1`}><div className={`text-3xl font-black ${c}`}>{n}</div><div className="mt-1 text-xs font-black uppercase tracking-wider text-slate-500">{l} accounts</div></div>)}</div>
{err&&<div className="mb-4 rounded-2xl bg-rose-50 p-4 text-sm text-rose-700">{err}</div>}
<div className="grid gap-5 lg:grid-cols-2">{rows.map((a,i)=><article key={a.id} className="rounded-3xl border border-blue-100 bg-white p-5 shadow-sm animate-[riseIn_.45s_ease-out]" style={{animationDelay:`${i*50}ms`}}><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2 font-black"><Activity size={17} className="text-indigo-500"/>{a.email}</div><div className="mt-1 text-xs text-slate-500">Daily {a.daily_send_limit} · Hourly {a.hourly_send_limit} · Total sent {a.total_sent}</div></div><span className={`rounded-full px-3 py-1 text-xs font-black ${a.health_status==="Healthy"?"bg-emerald-50 text-emerald-700":a.health_status==="Watch"?"bg-amber-50 text-amber-700":"bg-rose-50 text-rose-700"}`}>{a.health_status}</span></div>
<div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{[["Attempted",a.metrics.attempted],["Accepted",a.metrics.accepted],["Failures",a.metrics.failures],["Hard bounce",a.metrics.hard_bounces],["Soft bounce",a.metrics.soft_bounces],["Opens",a.metrics.opens],["Replies",a.metrics.replies],["Unsub",a.metrics.unsubscribes]].map(([l,n])=><div key={String(l)} className="rounded-2xl bg-slate-50 p-3"><div className="text-xl font-black tabular-nums">{n}</div><div className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{l}</div></div>)}</div>
<div className="mt-4 space-y-2"><div className="flex justify-between text-xs font-bold text-slate-500"><span>Provider acceptance</span><span>{pct(a.metrics.accepted,a.metrics.attempted)}%</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500 transition-all duration-700" style={{width:`${pct(a.metrics.accepted,a.metrics.attempted)}%`}}/></div></div>
<div className="mt-4 flex items-center gap-2 text-xs">{a.metrics.auth_ok?<span className="text-emerald-600"><ShieldCheck className="mr-1 inline" size={14}/>Authentication check available</span>:<span className="text-rose-600"><PauseCircle className="mr-1 inline" size={14}/>Authentication requires attention</span>}</div>
</article>)}</div></div></main>}
